/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_URL?.replace('https://', '').replace('.supabase.co', '')
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY